version: 2
jobs:
  build_node8:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/middy-reroute

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-v8-{{ checksum "package.json" }}
          - v1-dependencies-v8-
          - v1-dependencies-

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-v8-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: npm test

      - persist_to_workspace:
          root: ~/
          paths:
            - middy-reroute/*

  deploy:
    docker:
      - image: circleci/node:6.10

    steps:
        - attach_workspace:
            at: ~/

        - run:
            name: configure NPM registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

        - run:
            name: configure GitHub SSH
            command: mkdir -p ~/.ssh && ssh-keyscan -H github.com > ~/.ssh/known_hosts

        - run:
            working_directory: ~/middy-reroute
            name: publish
            command: |
              npm publish && npm run release:tag;


workflows:
  version: 2

  build_test_deploy:
    jobs:
        - build_node8
        - deploy:
            requires:
                - build_node8
            filters:
                branches:
                    only: master
